services:
  db:
    image: mysql:8
    container_name: coffee_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: coffee
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend/coffee/coffee
    container_name: coffee_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://coffee_db:3306/coffee?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8082:8082"

  frontend:
    build: ./fonend/frontend
    container_name: coffee_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      # Gọi backend qua tên container trong Docker network
      VITE_API_BASE_URL: http://coffee_backend:8082/api

volumes:
  mysql_data:
